alias ls='ls --color=auto'
PS1='[\u@\h \W]\$ '
alias vi='vim'
alias vim='nvim'
alias ll='ls -alh --color=auto'
alias vimz='vim ~/.zshrc'
alias sz='source ~/.zshrc'
alias cls='clear'
alias vimb='vim ~/.bashrc'
alias sb='source ~/.bashrc'
alias cdviml='cd ~/.local/share/nvim/site'
alias cdvimc='cd ~/.config/nvim'
alias vimi='vim ~/.config/nvim/init.vim'
